# this is to run the client development server against the deployed production server

version: '3'

services:
  client:
    container_name: bb-client
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: https://beat-bucket.herokuapp.com/
      REACT_APP_WEB_URL: http://localhost:3000/
